import { abordagem } from "./abordagem.js";
import { apresentacaoLoja } from "./apresentacaoLoja.js";
import { fechamento } from "./fechamento.js";
import { objecao } from "./objecao.js";
import { quebraGelo } from "./quebraGelo.js";
apresentacaoLoja();
quebraGelo();
abordagem();
objecao();
fechamento();